HOST_URL: http://localhost:3000

development:
  # db connection credentials
  POSTGRES_DB: dev_hello_tst_db
  # POSTGRES_DB: dev_todolist_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: '123456789'
test:
  TEST_POSTGRES_DB: test_hello_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: '123456789'

production:
  TEST_POSTGRES_DB: production_hello_db
  POSTGRES_USER: hello
  POSTGRES_PASSWORD: '123456789'