default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: postgres
  password: '123456789'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_development

test:
  <<: *default
  database: hello_test

production:
  <<: *default
  database: hello
  password: '111111'
